create table "public"."cleaning_reports" (
    "id" bigint generated by default as identity not null,
    "cleaning_schedule_id" bigint,
    "form_url" character varying,
    "comment" character varying,
    "created_at" timestamp without time zone default now(),
    "updated_at" timestamp without time zone default now()
);


alter table "public"."cleaning_reports" enable row level security;

CREATE UNIQUE INDEX cleaning_reports_pkey ON public.cleaning_reports USING btree (id);

alter table "public"."cleaning_reports" add constraint "cleaning_reports_pkey" PRIMARY KEY using index "cleaning_reports_pkey";

alter table "public"."cleaning_reports" add constraint "public_cleaning_reports_cleaning_schedule_id_fkey" FOREIGN KEY (cleaning_schedule_id) REFERENCES cleaning_schedules(id) not valid;

alter table "public"."cleaning_reports" validate constraint "public_cleaning_reports_cleaning_schedule_id_fkey";

grant delete on table "public"."cleaning_reports" to "anon";

grant insert on table "public"."cleaning_reports" to "anon";

grant references on table "public"."cleaning_reports" to "anon";

grant select on table "public"."cleaning_reports" to "anon";

grant trigger on table "public"."cleaning_reports" to "anon";

grant truncate on table "public"."cleaning_reports" to "anon";

grant update on table "public"."cleaning_reports" to "anon";

grant delete on table "public"."cleaning_reports" to "authenticated";

grant insert on table "public"."cleaning_reports" to "authenticated";

grant references on table "public"."cleaning_reports" to "authenticated";

grant select on table "public"."cleaning_reports" to "authenticated";

grant trigger on table "public"."cleaning_reports" to "authenticated";

grant truncate on table "public"."cleaning_reports" to "authenticated";

grant update on table "public"."cleaning_reports" to "authenticated";

grant delete on table "public"."cleaning_reports" to "service_role";

grant insert on table "public"."cleaning_reports" to "service_role";

grant references on table "public"."cleaning_reports" to "service_role";

grant select on table "public"."cleaning_reports" to "service_role";

grant trigger on table "public"."cleaning_reports" to "service_role";

grant truncate on table "public"."cleaning_reports" to "service_role";

grant update on table "public"."cleaning_reports" to "service_role";


